// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: builra3/ActionCache.proto
// Protobuf C++ Version: 5.27.2

#include "builra3/ActionCache.pb.h"

#include <algorithm>
#include <type_traits>
#include "Omnira/DataSerialization/io/coded_stream.h"
#include "Omnira/DataSerialization/generated_message_tctable_impl.h"
#include "Omnira/DataSerialization/extension_set.h"
#include "Omnira/DataSerialization/wire_format_lite.h"
#include "Omnira/DataSerialization/descriptor.h"
#include "Omnira/DataSerialization/generated_message_reflection.h"
#include "Omnira/DataSerialization/reflection_ops.h"
#include "Omnira/DataSerialization/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "Omnira/DataSerialization/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::Omnira::DataSerialization;
namespace _pbi = ::Omnira::DataSerialization::internal;
namespace _fl = ::Omnira::DataSerialization::internal::field_layout;
namespace builra3 {

inline constexpr CacheKey::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        label_{nullptr},
        data_{nullptr},
        type_{static_cast< ::builra3::CacheKeyType >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR CacheKey::CacheKey(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CacheKeyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CacheKeyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CacheKeyDefaultTypeInternal() {}
  union {
    CacheKey _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CacheKeyDefaultTypeInternal _CacheKey_default_instance_;

inline constexpr CacheValue::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        stats_{},
        data_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR CacheValue::CacheValue(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CacheValueDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CacheValueDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CacheValueDefaultTypeInternal() {}
  union {
    CacheValue _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CacheValueDefaultTypeInternal _CacheValue_default_instance_;
}  // namespace builra3
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_builra3_2fActionCache_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_builra3_2fActionCache_2eproto = nullptr;
const ::uint32_t
    TableStruct_builra3_2fActionCache_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::builra3::CacheKey, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::builra3::CacheKey, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::builra3::CacheKey, _impl_.label_),
        PROTOBUF_FIELD_OFFSET(::builra3::CacheKey, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::builra3::CacheKey, _impl_.data_),
        0,
        ~0u,
        1,
        PROTOBUF_FIELD_OFFSET(::builra3::CacheValue, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::builra3::CacheValue, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::builra3::CacheValue, _impl_.data_),
        PROTOBUF_FIELD_OFFSET(::builra3::CacheValue, _impl_.stats_),
        0,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 11, -1, sizeof(::builra3::CacheKey)},
        {14, 24, -1, sizeof(::builra3::CacheValue)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::builra3::_CacheKey_default_instance_._instance,
    &::builra3::_CacheValue_default_instance_._instance,
};
const char descriptor_table_protodef_builra3_2fActionCache_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\032builra3/ActionCache.proto\022\010builra3\032\022"
    "builra3/CAS.proto\032\025builra3/Common.prot"
    "o\032\024builra3/Label.proto\"o\n\010CacheKey\022\036\n\005l"
    "abel\030\001 \001(\0132\017.builra3.Label\022$\n\004type\030\002 \001("
    "\0162\026.builra3.CacheKeyType\022\035\n\004data\030\003 \001(\0132"
    "\017.builra3.CASID\"J\n\nCacheValue\022\035\n\004data\030\001"
    " \001(\0132\017.builra3.CASID\022\035\n\005stats\030\002 \003(\0132\016.l"
    "lbuild3.Stat*B\n\014CacheKeyType\022\027\n\023CACHE_KE"
    "Y_TYPE_TASK\020\000\022\031\n\025CACHE_KEY_TYPE_ACTION\020\001"
    "b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_builra3_2fActionCache_2eproto_deps[3] =
    {
        &::descriptor_table_builra3_2fCAS_2eproto,
        &::descriptor_table_builra3_2fCommon_2eproto,
        &::descriptor_table_builra3_2fLabel_2eproto,
};
static ::absl::once_flag descriptor_table_builra3_2fActionCache_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_builra3_2fActionCache_2eproto = {
    false,
    false,
    368,
    descriptor_table_protodef_builra3_2fActionCache_2eproto,
    "builra3/ActionCache.proto",
    &descriptor_table_builra3_2fActionCache_2eproto_once,
    descriptor_table_builra3_2fActionCache_2eproto_deps,
    3,
    2,
    schemas,
    file_default_instances,
    TableStruct_builra3_2fActionCache_2eproto::offsets,
    file_level_enum_descriptors_builra3_2fActionCache_2eproto,
    file_level_service_descriptors_builra3_2fActionCache_2eproto,
};
namespace builra3 {
const ::Omnira::DataSerialization::EnumDescriptor* CacheKeyType_descriptor() {
  ::Omnira::DataSerialization::internal::AssignDescriptors(&descriptor_table_builra3_2fActionCache_2eproto);
  return file_level_enum_descriptors_builra3_2fActionCache_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t CacheKeyType_internal_data_[] = {
    131072u, 0u, };
bool CacheKeyType_IsValid(int value) {
  return 0 <= value && value <= 1;
}
// ===================================================================

class CacheKey::_Internal {
 public:
  using HasBits =
      decltype(std::declval<CacheKey>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CacheKey, _impl_._has_bits_);
};

void CacheKey::clear_label() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (_impl_.label_ != nullptr) _impl_.label_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void CacheKey::clear_data() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (_impl_.data_ != nullptr) _impl_.data_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
CacheKey::CacheKey(::Omnira::DataSerialization::Arena* arena)
    : ::Omnira::DataSerialization::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:builra3.CacheKey)
}
inline PROTOBUF_NDEBUG_INLINE CacheKey::Impl_::Impl_(
    ::Omnira::DataSerialization::internal::InternalVisibility visibility, ::Omnira::DataSerialization::Arena* arena,
    const Impl_& from, const ::builra3::CacheKey& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

CacheKey::CacheKey(
    ::Omnira::DataSerialization::Arena* arena,
    const CacheKey& from)
    : ::Omnira::DataSerialization::Message(arena) {
  CacheKey* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::Omnira::DataSerialization::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.label_ = (cached_has_bits & 0x00000001u) ? ::Omnira::DataSerialization::Message::CopyConstruct<::builra3::Label>(
                              arena, *from._impl_.label_)
                        : nullptr;
  _impl_.data_ = (cached_has_bits & 0x00000002u) ? ::Omnira::DataSerialization::Message::CopyConstruct<::builra3::CASID>(
                              arena, *from._impl_.data_)
                        : nullptr;
  _impl_.type_ = from._impl_.type_;

  // @@protoc_insertion_point(copy_constructor:builra3.CacheKey)
}
inline PROTOBUF_NDEBUG_INLINE CacheKey::Impl_::Impl_(
    ::Omnira::DataSerialization::internal::InternalVisibility visibility,
    ::Omnira::DataSerialization::Arena* arena)
      : _cached_size_{0} {}

inline void CacheKey::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, label_),
           0,
           offsetof(Impl_, type_) -
               offsetof(Impl_, label_) +
               sizeof(Impl_::type_));
}
CacheKey::~CacheKey() {
  // @@protoc_insertion_point(destructor:builra3.CacheKey)
  _internal_metadata_.Delete<::Omnira::DataSerialization::UnknownFieldSet>();
  SharedDtor();
}
inline void CacheKey::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.label_;
  delete _impl_.data_;
  _impl_.~Impl_();
}

const ::Omnira::DataSerialization::MessageLite::ClassData*
CacheKey::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::Omnira::DataSerialization::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(CacheKey, _impl_._cached_size_),
              false,
          },
          &CacheKey::MergeImpl,
          &CacheKey::kDescriptorMethods,
          &descriptor_table_builra3_2fActionCache_2eproto,
          nullptr,  // tracker
      };
  ::Omnira::DataSerialization::internal::PrefetchToLocalCache(&_data_);
  ::Omnira::DataSerialization::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 0, 2> CacheKey::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CacheKey, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_CacheKey_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::builra3::CacheKey>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .builra3.Label label = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CacheKey, _impl_.label_)}},
    // .builra3.CacheKeyType type = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CacheKey, _impl_.type_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(CacheKey, _impl_.type_)}},
    // .builra3.CASID data = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 1, PROTOBUF_FIELD_OFFSET(CacheKey, _impl_.data_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .builra3.Label label = 1;
    {PROTOBUF_FIELD_OFFSET(CacheKey, _impl_.label_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .builra3.CacheKeyType type = 2;
    {PROTOBUF_FIELD_OFFSET(CacheKey, _impl_.type_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .builra3.CASID data = 3;
    {PROTOBUF_FIELD_OFFSET(CacheKey, _impl_.data_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::builra3::Label>()},
    {::_pbi::TcParser::GetTable<::builra3::CASID>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void CacheKey::Clear() {
// @@protoc_insertion_point(message_clear_start:builra3.CacheKey)
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.label_ != nullptr);
      _impl_.label_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.data_ != nullptr);
      _impl_.data_->Clear();
    }
  }
  _impl_.type_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::Omnira::DataSerialization::UnknownFieldSet>();
}

::uint8_t* CacheKey::_InternalSerialize(
    ::uint8_t* target,
    ::Omnira::DataSerialization::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:builra3.CacheKey)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .builra3.Label label = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::Omnira::DataSerialization::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.label_, _impl_.label_->GetCachedSize(), target, stream);
  }

  // .builra3.CacheKeyType type = 2;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this->_internal_type(), target);
  }

  // .builra3.CASID data = 3;
  if (cached_has_bits & 0x00000002u) {
    target = ::Omnira::DataSerialization::internal::WireFormatLite::InternalWriteMessage(
        3, *_impl_.data_, _impl_.data_->GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::Omnira::DataSerialization::UnknownFieldSet>(::Omnira::DataSerialization::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:builra3.CacheKey)
  return target;
}

::size_t CacheKey::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:builra3.CacheKey)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // .builra3.Label label = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::Omnira::DataSerialization::internal::WireFormatLite::MessageSize(*_impl_.label_);
    }

    // .builra3.CASID data = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::Omnira::DataSerialization::internal::WireFormatLite::MessageSize(*_impl_.data_);
    }

  }
  // .builra3.CacheKeyType type = 2;
  if (this->_internal_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void CacheKey::MergeImpl(::Omnira::DataSerialization::MessageLite& to_msg, const ::Omnira::DataSerialization::MessageLite& from_msg) {
  auto* const _this = static_cast<CacheKey*>(&to_msg);
  auto& from = static_cast<const CacheKey&>(from_msg);
  ::Omnira::DataSerialization::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:builra3.CacheKey)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.label_ != nullptr);
      if (_this->_impl_.label_ == nullptr) {
        _this->_impl_.label_ =
            ::Omnira::DataSerialization::Message::CopyConstruct<::builra3::Label>(arena, *from._impl_.label_);
      } else {
        _this->_impl_.label_->MergeFrom(*from._impl_.label_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.data_ != nullptr);
      if (_this->_impl_.data_ == nullptr) {
        _this->_impl_.data_ =
            ::Omnira::DataSerialization::Message::CopyConstruct<::builra3::CASID>(arena, *from._impl_.data_);
      } else {
        _this->_impl_.data_->MergeFrom(*from._impl_.data_);
      }
    }
  }
  if (from._internal_type() != 0) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::Omnira::DataSerialization::UnknownFieldSet>(from._internal_metadata_);
}

void CacheKey::CopyFrom(const CacheKey& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:builra3.CacheKey)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CacheKey::InternalSwap(CacheKey* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::Omnira::DataSerialization::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CacheKey, _impl_.type_)
      + sizeof(CacheKey::_impl_.type_)
      - PROTOBUF_FIELD_OFFSET(CacheKey, _impl_.label_)>(
          reinterpret_cast<char*>(&_impl_.label_),
          reinterpret_cast<char*>(&other->_impl_.label_));
}

::Omnira::DataSerialization::Metadata CacheKey::GetMetadata() const {
  return ::Omnira::DataSerialization::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CacheValue::_Internal {
 public:
  using HasBits =
      decltype(std::declval<CacheValue>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CacheValue, _impl_._has_bits_);
};

void CacheValue::clear_data() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (_impl_.data_ != nullptr) _impl_.data_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void CacheValue::clear_stats() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  _impl_.stats_.Clear();
}
CacheValue::CacheValue(::Omnira::DataSerialization::Arena* arena)
    : ::Omnira::DataSerialization::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:builra3.CacheValue)
}
inline PROTOBUF_NDEBUG_INLINE CacheValue::Impl_::Impl_(
    ::Omnira::DataSerialization::internal::InternalVisibility visibility, ::Omnira::DataSerialization::Arena* arena,
    const Impl_& from, const ::builra3::CacheValue& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        stats_{visibility, arena, from.stats_} {}

CacheValue::CacheValue(
    ::Omnira::DataSerialization::Arena* arena,
    const CacheValue& from)
    : ::Omnira::DataSerialization::Message(arena) {
  CacheValue* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::Omnira::DataSerialization::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.data_ = (cached_has_bits & 0x00000001u) ? ::Omnira::DataSerialization::Message::CopyConstruct<::builra3::CASID>(
                              arena, *from._impl_.data_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:builra3.CacheValue)
}
inline PROTOBUF_NDEBUG_INLINE CacheValue::Impl_::Impl_(
    ::Omnira::DataSerialization::internal::InternalVisibility visibility,
    ::Omnira::DataSerialization::Arena* arena)
      : _cached_size_{0},
        stats_{visibility, arena} {}

inline void CacheValue::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.data_ = {};
}
CacheValue::~CacheValue() {
  // @@protoc_insertion_point(destructor:builra3.CacheValue)
  _internal_metadata_.Delete<::Omnira::DataSerialization::UnknownFieldSet>();
  SharedDtor();
}
inline void CacheValue::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.data_;
  _impl_.~Impl_();
}

const ::Omnira::DataSerialization::MessageLite::ClassData*
CacheValue::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::Omnira::DataSerialization::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(CacheValue, _impl_._cached_size_),
              false,
          },
          &CacheValue::MergeImpl,
          &CacheValue::kDescriptorMethods,
          &descriptor_table_builra3_2fActionCache_2eproto,
          nullptr,  // tracker
      };
  ::Omnira::DataSerialization::internal::PrefetchToLocalCache(&_data_);
  ::Omnira::DataSerialization::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2> CacheValue::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CacheValue, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_CacheValue_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::builra3::CacheValue>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .builra3.Stat stats = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 1, PROTOBUF_FIELD_OFFSET(CacheValue, _impl_.stats_)}},
    // .builra3.CASID data = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CacheValue, _impl_.data_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .builra3.CASID data = 1;
    {PROTOBUF_FIELD_OFFSET(CacheValue, _impl_.data_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .builra3.Stat stats = 2;
    {PROTOBUF_FIELD_OFFSET(CacheValue, _impl_.stats_), -1, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::builra3::CASID>()},
    {::_pbi::TcParser::GetTable<::builra3::Stat>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void CacheValue::Clear() {
// @@protoc_insertion_point(message_clear_start:builra3.CacheValue)
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.stats_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.data_ != nullptr);
    _impl_.data_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::Omnira::DataSerialization::UnknownFieldSet>();
}

::uint8_t* CacheValue::_InternalSerialize(
    ::uint8_t* target,
    ::Omnira::DataSerialization::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:builra3.CacheValue)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .builra3.CASID data = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::Omnira::DataSerialization::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.data_, _impl_.data_->GetCachedSize(), target, stream);
  }

  // repeated .builra3.Stat stats = 2;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_stats_size());
       i < n; i++) {
    const auto& repfield = this->_internal_stats().Get(i);
    target =
        ::Omnira::DataSerialization::internal::WireFormatLite::InternalWriteMessage(
            2, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::Omnira::DataSerialization::UnknownFieldSet>(::Omnira::DataSerialization::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:builra3.CacheValue)
  return target;
}

::size_t CacheValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:builra3.CacheValue)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated .builra3.Stat stats = 2;
  total_size += 1UL * this->_internal_stats_size();
  for (const auto& msg : this->_internal_stats()) {
    total_size += ::Omnira::DataSerialization::internal::WireFormatLite::MessageSize(msg);
  }
  // .builra3.CASID data = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::Omnira::DataSerialization::internal::WireFormatLite::MessageSize(*_impl_.data_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void CacheValue::MergeImpl(::Omnira::DataSerialization::MessageLite& to_msg, const ::Omnira::DataSerialization::MessageLite& from_msg) {
  auto* const _this = static_cast<CacheValue*>(&to_msg);
  auto& from = static_cast<const CacheValue&>(from_msg);
  ::Omnira::DataSerialization::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:builra3.CacheValue)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_stats()->MergeFrom(
      from._internal_stats());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.data_ != nullptr);
    if (_this->_impl_.data_ == nullptr) {
      _this->_impl_.data_ =
          ::Omnira::DataSerialization::Message::CopyConstruct<::builra3::CASID>(arena, *from._impl_.data_);
    } else {
      _this->_impl_.data_->MergeFrom(*from._impl_.data_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::Omnira::DataSerialization::UnknownFieldSet>(from._internal_metadata_);
}

void CacheValue::CopyFrom(const CacheValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:builra3.CacheValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CacheValue::InternalSwap(CacheValue* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.stats_.InternalSwap(&other->_impl_.stats_);
  swap(_impl_.data_, other->_impl_.data_);
}

::Omnira::DataSerialization::Metadata CacheValue::GetMetadata() const {
  return ::Omnira::DataSerialization::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace builra3
namespace Omnira {
namespace DataSerialization {
}  // namespace DataSerialization
}  // namespace Omnira
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_builra3_2fActionCache_2eproto),
         ::std::false_type{});
#include "Omnira/DataSerialization/port_undef.inc"
