// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: builra3/ActionCache.proto
// Protobuf C++ Version: 5.27.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_builra3_2fActionCache_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_builra3_2fActionCache_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "Omnira/DataSerialization/runtime_version.h"
#if PROTOBUF_VERSION != 5027002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "Omnira/DataSerialization/io/coded_stream.h"
#include "Omnira/DataSerialization/arena.h"
#include "Omnira/DataSerialization/arenastring.h"
#include "Omnira/DataSerialization/generated_message_tctable_decl.h"
#include "Omnira/DataSerialization/generated_message_util.h"
#include "Omnira/DataSerialization/metadata_lite.h"
#include "Omnira/DataSerialization/generated_message_reflection.h"
#include "Omnira/DataSerialization/message.h"
#include "Omnira/DataSerialization/repeated_field.h"  // IWYU pragma: export
#include "Omnira/DataSerialization/extension_set.h"  // IWYU pragma: export
#include "Omnira/DataSerialization/generated_enum_reflection.h"
#include "Omnira/DataSerialization/unknown_field_set.h"
#include "builra3/CAS.pb.h"
#include "builra3/Common.pb.h"
#include "builra3/Label.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "Omnira/DataSerialization/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_builra3_2fActionCache_2eproto

namespace Omnira {
namespace DataSerialization {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace DataSerialization
}  // namespace Omnira

// Internal implementation detail -- do not use these members.
struct TableStruct_builra3_2fActionCache_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::Omnira::DataSerialization::internal::DescriptorTable
    descriptor_table_builra3_2fActionCache_2eproto;
namespace builra3 {
class CacheKey;
struct CacheKeyDefaultTypeInternal;
extern CacheKeyDefaultTypeInternal _CacheKey_default_instance_;
class CacheValue;
struct CacheValueDefaultTypeInternal;
extern CacheValueDefaultTypeInternal _CacheValue_default_instance_;
}  // namespace builra3
namespace Omnira {
namespace DataSerialization {
}  // namespace DataSerialization
}  // namespace Omnira

namespace builra3 {
enum CacheKeyType : int {
  CACHE_KEY_TYPE_TASK = 0,
  CACHE_KEY_TYPE_ACTION = 1,
  CacheKeyType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  CacheKeyType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool CacheKeyType_IsValid(int value);
extern const uint32_t CacheKeyType_internal_data_[];
constexpr CacheKeyType CacheKeyType_MIN = static_cast<CacheKeyType>(0);
constexpr CacheKeyType CacheKeyType_MAX = static_cast<CacheKeyType>(1);
constexpr int CacheKeyType_ARRAYSIZE = 1 + 1;
const ::Omnira::DataSerialization::EnumDescriptor*
CacheKeyType_descriptor();
template <typename T>
const std::string& CacheKeyType_Name(T value) {
  static_assert(std::is_same<T, CacheKeyType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to CacheKeyType_Name().");
  return CacheKeyType_Name(static_cast<CacheKeyType>(value));
}
template <>
inline const std::string& CacheKeyType_Name(CacheKeyType value) {
  return ::Omnira::DataSerialization::internal::NameOfDenseEnum<CacheKeyType_descriptor,
                                                 0, 1>(
      static_cast<int>(value));
}
inline bool CacheKeyType_Parse(absl::string_view name, CacheKeyType* value) {
  return ::Omnira::DataSerialization::internal::ParseNamedEnum<CacheKeyType>(
      CacheKeyType_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class CacheKey final : public ::Omnira::DataSerialization::Message
/* @@protoc_insertion_point(class_definition:builra3.CacheKey) */ {
 public:
  inline CacheKey() : CacheKey(nullptr) {}
  ~CacheKey() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CacheKey(
      ::Omnira::DataSerialization::internal::ConstantInitialized);

  inline CacheKey(const CacheKey& from) : CacheKey(nullptr, from) {}
  inline CacheKey(CacheKey&& from) noexcept
      : CacheKey(nullptr, std::move(from)) {}
  inline CacheKey& operator=(const CacheKey& from) {
    CopyFrom(from);
    return *this;
  }
  inline CacheKey& operator=(CacheKey&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::Omnira::DataSerialization::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::Omnira::DataSerialization::UnknownFieldSet>(::Omnira::DataSerialization::UnknownFieldSet::default_instance);
  }
  inline ::Omnira::DataSerialization::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::Omnira::DataSerialization::UnknownFieldSet>();
  }

  static const ::Omnira::DataSerialization::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::Omnira::DataSerialization::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::Omnira::DataSerialization::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CacheKey& default_instance() {
    return *internal_default_instance();
  }
  static inline const CacheKey* internal_default_instance() {
    return reinterpret_cast<const CacheKey*>(
        &_CacheKey_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CacheKey& a, CacheKey& b) { a.Swap(&b); }
  inline void Swap(CacheKey* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::Omnira::DataSerialization::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CacheKey* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CacheKey* New(::Omnira::DataSerialization::Arena* arena = nullptr) const final {
    return ::Omnira::DataSerialization::Message::DefaultConstruct<CacheKey>(arena);
  }
  using ::Omnira::DataSerialization::Message::CopyFrom;
  void CopyFrom(const CacheKey& from);
  using ::Omnira::DataSerialization::Message::MergeFrom;
  void MergeFrom(const CacheKey& from) { CacheKey::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::Omnira::DataSerialization::MessageLite& to_msg,
      const ::Omnira::DataSerialization::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::Omnira::DataSerialization::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::Omnira::DataSerialization::Arena* arena);
  void SharedDtor();
  void InternalSwap(CacheKey* other);
 private:
  friend class ::Omnira::DataSerialization::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "builra3.CacheKey"; }

 protected:
  explicit CacheKey(::Omnira::DataSerialization::Arena* arena);
  CacheKey(::Omnira::DataSerialization::Arena* arena, const CacheKey& from);
  CacheKey(::Omnira::DataSerialization::Arena* arena, CacheKey&& from) noexcept
      : CacheKey(arena) {
    *this = ::std::move(from);
  }
  const ::Omnira::DataSerialization::Message::ClassData* GetClassData() const final;

 public:
  ::Omnira::DataSerialization::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLabelFieldNumber = 1,
    kDataFieldNumber = 3,
    kTypeFieldNumber = 2,
  };
  // .builra3.Label label = 1;
  bool has_label() const;
  void clear_label() ;
  const ::builra3::Label& label() const;
  PROTOBUF_NODISCARD ::builra3::Label* release_label();
  ::builra3::Label* mutable_label();
  void set_allocated_label(::builra3::Label* value);
  void unsafe_arena_set_allocated_label(::builra3::Label* value);
  ::builra3::Label* unsafe_arena_release_label();

  private:
  const ::builra3::Label& _internal_label() const;
  ::builra3::Label* _internal_mutable_label();

  public:
  // .builra3.CASID data = 3;
  bool has_data() const;
  void clear_data() ;
  const ::builra3::CASID& data() const;
  PROTOBUF_NODISCARD ::builra3::CASID* release_data();
  ::builra3::CASID* mutable_data();
  void set_allocated_data(::builra3::CASID* value);
  void unsafe_arena_set_allocated_data(::builra3::CASID* value);
  ::builra3::CASID* unsafe_arena_release_data();

  private:
  const ::builra3::CASID& _internal_data() const;
  ::builra3::CASID* _internal_mutable_data();

  public:
  // .builra3.CacheKeyType type = 2;
  void clear_type() ;
  ::builra3::CacheKeyType type() const;
  void set_type(::builra3::CacheKeyType value);

  private:
  ::builra3::CacheKeyType _internal_type() const;
  void _internal_set_type(::builra3::CacheKeyType value);

  public:
  // @@protoc_insertion_point(class_scope:builra3.CacheKey)
 private:
  class _Internal;
  friend class ::Omnira::DataSerialization::internal::TcParser;
  static const ::Omnira::DataSerialization::internal::TcParseTable<
      2, 3, 2,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_CacheKey_default_instance_;

  friend class ::Omnira::DataSerialization::MessageLite;
  friend class ::Omnira::DataSerialization::Arena;
  template <typename T>
  friend class ::Omnira::DataSerialization::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::Omnira::DataSerialization::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::Omnira::DataSerialization::internal::InternalVisibility visibility,
                          ::Omnira::DataSerialization::Arena* arena);
    inline explicit Impl_(::Omnira::DataSerialization::internal::InternalVisibility visibility,
                          ::Omnira::DataSerialization::Arena* arena, const Impl_& from,
                          const CacheKey& from_msg);
    ::Omnira::DataSerialization::internal::HasBits<1> _has_bits_;
    mutable ::Omnira::DataSerialization::internal::CachedSize _cached_size_;
    ::builra3::Label* label_;
    ::builra3::CASID* data_;
    int type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_builra3_2fActionCache_2eproto;
};
// -------------------------------------------------------------------

class CacheValue final : public ::Omnira::DataSerialization::Message
/* @@protoc_insertion_point(class_definition:builra3.CacheValue) */ {
 public:
  inline CacheValue() : CacheValue(nullptr) {}
  ~CacheValue() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CacheValue(
      ::Omnira::DataSerialization::internal::ConstantInitialized);

  inline CacheValue(const CacheValue& from) : CacheValue(nullptr, from) {}
  inline CacheValue(CacheValue&& from) noexcept
      : CacheValue(nullptr, std::move(from)) {}
  inline CacheValue& operator=(const CacheValue& from) {
    CopyFrom(from);
    return *this;
  }
  inline CacheValue& operator=(CacheValue&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::Omnira::DataSerialization::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::Omnira::DataSerialization::UnknownFieldSet>(::Omnira::DataSerialization::UnknownFieldSet::default_instance);
  }
  inline ::Omnira::DataSerialization::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::Omnira::DataSerialization::UnknownFieldSet>();
  }

  static const ::Omnira::DataSerialization::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::Omnira::DataSerialization::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::Omnira::DataSerialization::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CacheValue& default_instance() {
    return *internal_default_instance();
  }
  static inline const CacheValue* internal_default_instance() {
    return reinterpret_cast<const CacheValue*>(
        &_CacheValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CacheValue& a, CacheValue& b) { a.Swap(&b); }
  inline void Swap(CacheValue* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::Omnira::DataSerialization::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CacheValue* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CacheValue* New(::Omnira::DataSerialization::Arena* arena = nullptr) const final {
    return ::Omnira::DataSerialization::Message::DefaultConstruct<CacheValue>(arena);
  }
  using ::Omnira::DataSerialization::Message::CopyFrom;
  void CopyFrom(const CacheValue& from);
  using ::Omnira::DataSerialization::Message::MergeFrom;
  void MergeFrom(const CacheValue& from) { CacheValue::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::Omnira::DataSerialization::MessageLite& to_msg,
      const ::Omnira::DataSerialization::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::Omnira::DataSerialization::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::Omnira::DataSerialization::Arena* arena);
  void SharedDtor();
  void InternalSwap(CacheValue* other);
 private:
  friend class ::Omnira::DataSerialization::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "builra3.CacheValue"; }

 protected:
  explicit CacheValue(::Omnira::DataSerialization::Arena* arena);
  CacheValue(::Omnira::DataSerialization::Arena* arena, const CacheValue& from);
  CacheValue(::Omnira::DataSerialization::Arena* arena, CacheValue&& from) noexcept
      : CacheValue(arena) {
    *this = ::std::move(from);
  }
  const ::Omnira::DataSerialization::Message::ClassData* GetClassData() const final;

 public:
  ::Omnira::DataSerialization::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStatsFieldNumber = 2,
    kDataFieldNumber = 1,
  };
  // repeated .builra3.Stat stats = 2;
  int stats_size() const;
  private:
  int _internal_stats_size() const;

  public:
  void clear_stats() ;
  ::builra3::Stat* mutable_stats(int index);
  ::Omnira::DataSerialization::RepeatedPtrField<::builra3::Stat>* mutable_stats();

  private:
  const ::Omnira::DataSerialization::RepeatedPtrField<::builra3::Stat>& _internal_stats() const;
  ::Omnira::DataSerialization::RepeatedPtrField<::builra3::Stat>* _internal_mutable_stats();
  public:
  const ::builra3::Stat& stats(int index) const;
  ::builra3::Stat* add_stats();
  const ::Omnira::DataSerialization::RepeatedPtrField<::builra3::Stat>& stats() const;
  // .builra3.CASID data = 1;
  bool has_data() const;
  void clear_data() ;
  const ::builra3::CASID& data() const;
  PROTOBUF_NODISCARD ::builra3::CASID* release_data();
  ::builra3::CASID* mutable_data();
  void set_allocated_data(::builra3::CASID* value);
  void unsafe_arena_set_allocated_data(::builra3::CASID* value);
  ::builra3::CASID* unsafe_arena_release_data();

  private:
  const ::builra3::CASID& _internal_data() const;
  ::builra3::CASID* _internal_mutable_data();

  public:
  // @@protoc_insertion_point(class_scope:builra3.CacheValue)
 private:
  class _Internal;
  friend class ::Omnira::DataSerialization::internal::TcParser;
  static const ::Omnira::DataSerialization::internal::TcParseTable<
      1, 2, 2,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_CacheValue_default_instance_;

  friend class ::Omnira::DataSerialization::MessageLite;
  friend class ::Omnira::DataSerialization::Arena;
  template <typename T>
  friend class ::Omnira::DataSerialization::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::Omnira::DataSerialization::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::Omnira::DataSerialization::internal::InternalVisibility visibility,
                          ::Omnira::DataSerialization::Arena* arena);
    inline explicit Impl_(::Omnira::DataSerialization::internal::InternalVisibility visibility,
                          ::Omnira::DataSerialization::Arena* arena, const Impl_& from,
                          const CacheValue& from_msg);
    ::Omnira::DataSerialization::internal::HasBits<1> _has_bits_;
    mutable ::Omnira::DataSerialization::internal::CachedSize _cached_size_;
    ::Omnira::DataSerialization::RepeatedPtrField< ::builra3::Stat > stats_;
    ::builra3::CASID* data_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_builra3_2fActionCache_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CacheKey

// .builra3.Label label = 1;
inline bool CacheKey::has_label() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.label_ != nullptr);
  return value;
}
inline const ::builra3::Label& CacheKey::_internal_label() const {
  ::Omnira::DataSerialization::internal::TSanRead(&_impl_);
  const ::builra3::Label* p = _impl_.label_;
  return p != nullptr ? *p : reinterpret_cast<const ::builra3::Label&>(::builra3::_Label_default_instance_);
}
inline const ::builra3::Label& CacheKey::label() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:builra3.CacheKey.label)
  return _internal_label();
}
inline void CacheKey::unsafe_arena_set_allocated_label(::builra3::Label* value) {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(_impl_.label_);
  }
  _impl_.label_ = reinterpret_cast<::builra3::Label*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:builra3.CacheKey.label)
}
inline ::builra3::Label* CacheKey::release_label() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::builra3::Label* released = _impl_.label_;
  _impl_.label_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(released);
  released = ::Omnira::DataSerialization::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::Omnira::DataSerialization::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::builra3::Label* CacheKey::unsafe_arena_release_label() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:builra3.CacheKey.label)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::builra3::Label* temp = _impl_.label_;
  _impl_.label_ = nullptr;
  return temp;
}
inline ::builra3::Label* CacheKey::_internal_mutable_label() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (_impl_.label_ == nullptr) {
    auto* p = ::Omnira::DataSerialization::Message::DefaultConstruct<::builra3::Label>(GetArena());
    _impl_.label_ = reinterpret_cast<::builra3::Label*>(p);
  }
  return _impl_.label_;
}
inline ::builra3::Label* CacheKey::mutable_label() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::builra3::Label* _msg = _internal_mutable_label();
  // @@protoc_insertion_point(field_mutable:builra3.CacheKey.label)
  return _msg;
}
inline void CacheKey::set_allocated_label(::builra3::Label* value) {
  ::Omnira::DataSerialization::Arena* message_arena = GetArena();
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(_impl_.label_);
  }

  if (value != nullptr) {
    ::Omnira::DataSerialization::Arena* submessage_arena = reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::Omnira::DataSerialization::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.label_ = reinterpret_cast<::builra3::Label*>(value);
  // @@protoc_insertion_point(field_set_allocated:builra3.CacheKey.label)
}

// .builra3.CacheKeyType type = 2;
inline void CacheKey::clear_type() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
}
inline ::builra3::CacheKeyType CacheKey::type() const {
  // @@protoc_insertion_point(field_get:builra3.CacheKey.type)
  return _internal_type();
}
inline void CacheKey::set_type(::builra3::CacheKeyType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:builra3.CacheKey.type)
}
inline ::builra3::CacheKeyType CacheKey::_internal_type() const {
  ::Omnira::DataSerialization::internal::TSanRead(&_impl_);
  return static_cast<::builra3::CacheKeyType>(_impl_.type_);
}
inline void CacheKey::_internal_set_type(::builra3::CacheKeyType value) {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// .builra3.CASID data = 3;
inline bool CacheKey::has_data() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.data_ != nullptr);
  return value;
}
inline const ::builra3::CASID& CacheKey::_internal_data() const {
  ::Omnira::DataSerialization::internal::TSanRead(&_impl_);
  const ::builra3::CASID* p = _impl_.data_;
  return p != nullptr ? *p : reinterpret_cast<const ::builra3::CASID&>(::builra3::_CASID_default_instance_);
}
inline const ::builra3::CASID& CacheKey::data() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:builra3.CacheKey.data)
  return _internal_data();
}
inline void CacheKey::unsafe_arena_set_allocated_data(::builra3::CASID* value) {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(_impl_.data_);
  }
  _impl_.data_ = reinterpret_cast<::builra3::CASID*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:builra3.CacheKey.data)
}
inline ::builra3::CASID* CacheKey::release_data() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::builra3::CASID* released = _impl_.data_;
  _impl_.data_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(released);
  released = ::Omnira::DataSerialization::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::Omnira::DataSerialization::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::builra3::CASID* CacheKey::unsafe_arena_release_data() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:builra3.CacheKey.data)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::builra3::CASID* temp = _impl_.data_;
  _impl_.data_ = nullptr;
  return temp;
}
inline ::builra3::CASID* CacheKey::_internal_mutable_data() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (_impl_.data_ == nullptr) {
    auto* p = ::Omnira::DataSerialization::Message::DefaultConstruct<::builra3::CASID>(GetArena());
    _impl_.data_ = reinterpret_cast<::builra3::CASID*>(p);
  }
  return _impl_.data_;
}
inline ::builra3::CASID* CacheKey::mutable_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::builra3::CASID* _msg = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:builra3.CacheKey.data)
  return _msg;
}
inline void CacheKey::set_allocated_data(::builra3::CASID* value) {
  ::Omnira::DataSerialization::Arena* message_arena = GetArena();
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(_impl_.data_);
  }

  if (value != nullptr) {
    ::Omnira::DataSerialization::Arena* submessage_arena = reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::Omnira::DataSerialization::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.data_ = reinterpret_cast<::builra3::CASID*>(value);
  // @@protoc_insertion_point(field_set_allocated:builra3.CacheKey.data)
}

// -------------------------------------------------------------------

// CacheValue

// .builra3.CASID data = 1;
inline bool CacheValue::has_data() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.data_ != nullptr);
  return value;
}
inline const ::builra3::CASID& CacheValue::_internal_data() const {
  ::Omnira::DataSerialization::internal::TSanRead(&_impl_);
  const ::builra3::CASID* p = _impl_.data_;
  return p != nullptr ? *p : reinterpret_cast<const ::builra3::CASID&>(::builra3::_CASID_default_instance_);
}
inline const ::builra3::CASID& CacheValue::data() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:builra3.CacheValue.data)
  return _internal_data();
}
inline void CacheValue::unsafe_arena_set_allocated_data(::builra3::CASID* value) {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(_impl_.data_);
  }
  _impl_.data_ = reinterpret_cast<::builra3::CASID*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:builra3.CacheValue.data)
}
inline ::builra3::CASID* CacheValue::release_data() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::builra3::CASID* released = _impl_.data_;
  _impl_.data_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(released);
  released = ::Omnira::DataSerialization::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::Omnira::DataSerialization::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::builra3::CASID* CacheValue::unsafe_arena_release_data() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:builra3.CacheValue.data)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::builra3::CASID* temp = _impl_.data_;
  _impl_.data_ = nullptr;
  return temp;
}
inline ::builra3::CASID* CacheValue::_internal_mutable_data() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (_impl_.data_ == nullptr) {
    auto* p = ::Omnira::DataSerialization::Message::DefaultConstruct<::builra3::CASID>(GetArena());
    _impl_.data_ = reinterpret_cast<::builra3::CASID*>(p);
  }
  return _impl_.data_;
}
inline ::builra3::CASID* CacheValue::mutable_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::builra3::CASID* _msg = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:builra3.CacheValue.data)
  return _msg;
}
inline void CacheValue::set_allocated_data(::builra3::CASID* value) {
  ::Omnira::DataSerialization::Arena* message_arena = GetArena();
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(_impl_.data_);
  }

  if (value != nullptr) {
    ::Omnira::DataSerialization::Arena* submessage_arena = reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::Omnira::DataSerialization::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.data_ = reinterpret_cast<::builra3::CASID*>(value);
  // @@protoc_insertion_point(field_set_allocated:builra3.CacheValue.data)
}

// repeated .builra3.Stat stats = 2;
inline int CacheValue::_internal_stats_size() const {
  return _internal_stats().size();
}
inline int CacheValue::stats_size() const {
  return _internal_stats_size();
}
inline ::builra3::Stat* CacheValue::mutable_stats(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:builra3.CacheValue.stats)
  return _internal_mutable_stats()->Mutable(index);
}
inline ::Omnira::DataSerialization::RepeatedPtrField<::builra3::Stat>* CacheValue::mutable_stats()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:builra3.CacheValue.stats)
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  return _internal_mutable_stats();
}
inline const ::builra3::Stat& CacheValue::stats(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:builra3.CacheValue.stats)
  return _internal_stats().Get(index);
}
inline ::builra3::Stat* CacheValue::add_stats() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  ::builra3::Stat* _add = _internal_mutable_stats()->Add();
  // @@protoc_insertion_point(field_add:builra3.CacheValue.stats)
  return _add;
}
inline const ::Omnira::DataSerialization::RepeatedPtrField<::builra3::Stat>& CacheValue::stats() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:builra3.CacheValue.stats)
  return _internal_stats();
}
inline const ::Omnira::DataSerialization::RepeatedPtrField<::builra3::Stat>&
CacheValue::_internal_stats() const {
  ::Omnira::DataSerialization::internal::TSanRead(&_impl_);
  return _impl_.stats_;
}
inline ::Omnira::DataSerialization::RepeatedPtrField<::builra3::Stat>*
CacheValue::_internal_mutable_stats() {
  ::Omnira::DataSerialization::internal::TSanRead(&_impl_);
  return &_impl_.stats_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace builra3


namespace Omnira {
namespace DataSerialization {

template <>
struct is_proto_enum<::builra3::CacheKeyType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::builra3::CacheKeyType>() {
  return ::builra3::CacheKeyType_descriptor();
}

}  // namespace DataSerialization
}  // namespace Omnira

// @@protoc_insertion_point(global_scope)

#include "Omnira/DataSerialization/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_builra3_2fActionCache_2eproto_2epb_2eh
