// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: builra3/EngineInternal.proto
// Protobuf C++ Version: 5.27.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_builra3_2fEngineInternal_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_builra3_2fEngineInternal_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "Omnira/DataSerialization/runtime_version.h"
#if PROTOBUF_VERSION != 5027002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "Omnira/DataSerialization/io/coded_stream.h"
#include "Omnira/DataSerialization/arena.h"
#include "Omnira/DataSerialization/arenastring.h"
#include "Omnira/DataSerialization/generated_message_tctable_decl.h"
#include "Omnira/DataSerialization/generated_message_util.h"
#include "Omnira/DataSerialization/metadata_lite.h"
#include "Omnira/DataSerialization/generated_message_reflection.h"
#include "Omnira/DataSerialization/message.h"
#include "Omnira/DataSerialization/repeated_field.h"  // IWYU pragma: export
#include "Omnira/DataSerialization/extension_set.h"  // IWYU pragma: export
#include "Omnira/DataSerialization/unknown_field_set.h"
#include "builra3/Action.pb.h"
#include "builra3/Engine.pb.h"
#include "builra3/Label.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "Omnira/DataSerialization/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_builra3_2fEngineInternal_2eproto

namespace Omnira {
namespace DataSerialization {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace DataSerialization
}  // namespace Omnira

// Internal implementation detail -- do not use these members.
struct TableStruct_builra3_2fEngineInternal_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::Omnira::DataSerialization::internal::DescriptorTable
    descriptor_table_builra3_2fEngineInternal_2eproto;
namespace builra3 {
class TaskArtifactRequest;
struct TaskArtifactRequestDefaultTypeInternal;
extern TaskArtifactRequestDefaultTypeInternal _TaskArtifactRequest_default_instance_;
class TaskRequest;
struct TaskRequestDefaultTypeInternal;
extern TaskRequestDefaultTypeInternal _TaskRequest_default_instance_;
class TaskRuleRequest;
struct TaskRuleRequestDefaultTypeInternal;
extern TaskRuleRequestDefaultTypeInternal _TaskRuleRequest_default_instance_;
class TaskTransitionKey;
struct TaskTransitionKeyDefaultTypeInternal;
extern TaskTransitionKeyDefaultTypeInternal _TaskTransitionKey_default_instance_;
class TaskTransitionValue;
struct TaskTransitionValueDefaultTypeInternal;
extern TaskTransitionValueDefaultTypeInternal _TaskTransitionValue_default_instance_;
}  // namespace builra3
namespace Omnira {
namespace DataSerialization {
}  // namespace DataSerialization
}  // namespace Omnira

namespace builra3 {

// ===================================================================


// -------------------------------------------------------------------

class TaskRuleRequest final : public ::Omnira::DataSerialization::Message
/* @@protoc_insertion_point(class_definition:builra3.TaskRuleRequest) */ {
 public:
  inline TaskRuleRequest() : TaskRuleRequest(nullptr) {}
  ~TaskRuleRequest() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TaskRuleRequest(
      ::Omnira::DataSerialization::internal::ConstantInitialized);

  inline TaskRuleRequest(const TaskRuleRequest& from) : TaskRuleRequest(nullptr, from) {}
  inline TaskRuleRequest(TaskRuleRequest&& from) noexcept
      : TaskRuleRequest(nullptr, std::move(from)) {}
  inline TaskRuleRequest& operator=(const TaskRuleRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline TaskRuleRequest& operator=(TaskRuleRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::Omnira::DataSerialization::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::Omnira::DataSerialization::UnknownFieldSet>(::Omnira::DataSerialization::UnknownFieldSet::default_instance);
  }
  inline ::Omnira::DataSerialization::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::Omnira::DataSerialization::UnknownFieldSet>();
  }

  static const ::Omnira::DataSerialization::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::Omnira::DataSerialization::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::Omnira::DataSerialization::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TaskRuleRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const TaskRuleRequest* internal_default_instance() {
    return reinterpret_cast<const TaskRuleRequest*>(
        &_TaskRuleRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(TaskRuleRequest& a, TaskRuleRequest& b) { a.Swap(&b); }
  inline void Swap(TaskRuleRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::Omnira::DataSerialization::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TaskRuleRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TaskRuleRequest* New(::Omnira::DataSerialization::Arena* arena = nullptr) const final {
    return ::Omnira::DataSerialization::Message::DefaultConstruct<TaskRuleRequest>(arena);
  }
  using ::Omnira::DataSerialization::Message::CopyFrom;
  void CopyFrom(const TaskRuleRequest& from);
  using ::Omnira::DataSerialization::Message::MergeFrom;
  void MergeFrom(const TaskRuleRequest& from) { TaskRuleRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::Omnira::DataSerialization::MessageLite& to_msg,
      const ::Omnira::DataSerialization::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::Omnira::DataSerialization::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::Omnira::DataSerialization::Arena* arena);
  void SharedDtor();
  void InternalSwap(TaskRuleRequest* other);
 private:
  friend class ::Omnira::DataSerialization::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "builra3.TaskRuleRequest"; }

 protected:
  explicit TaskRuleRequest(::Omnira::DataSerialization::Arena* arena);
  TaskRuleRequest(::Omnira::DataSerialization::Arena* arena, const TaskRuleRequest& from);
  TaskRuleRequest(::Omnira::DataSerialization::Arena* arena, TaskRuleRequest&& from) noexcept
      : TaskRuleRequest(arena) {
    *this = ::std::move(from);
  }
  const ::Omnira::DataSerialization::Message::ClassData* GetClassData() const final;

 public:
  ::Omnira::DataSerialization::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLabelFieldNumber = 1,
  };
  // .builra3.Label label = 1;
  bool has_label() const;
  void clear_label() ;
  const ::builra3::Label& label() const;
  PROTOBUF_NODISCARD ::builra3::Label* release_label();
  ::builra3::Label* mutable_label();
  void set_allocated_label(::builra3::Label* value);
  void unsafe_arena_set_allocated_label(::builra3::Label* value);
  ::builra3::Label* unsafe_arena_release_label();

  private:
  const ::builra3::Label& _internal_label() const;
  ::builra3::Label* _internal_mutable_label();

  public:
  // @@protoc_insertion_point(class_scope:builra3.TaskRuleRequest)
 private:
  class _Internal;
  friend class ::Omnira::DataSerialization::internal::TcParser;
  static const ::Omnira::DataSerialization::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_TaskRuleRequest_default_instance_;

  friend class ::Omnira::DataSerialization::MessageLite;
  friend class ::Omnira::DataSerialization::Arena;
  template <typename T>
  friend class ::Omnira::DataSerialization::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::Omnira::DataSerialization::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::Omnira::DataSerialization::internal::InternalVisibility visibility,
                          ::Omnira::DataSerialization::Arena* arena);
    inline explicit Impl_(::Omnira::DataSerialization::internal::InternalVisibility visibility,
                          ::Omnira::DataSerialization::Arena* arena, const Impl_& from,
                          const TaskRuleRequest& from_msg);
    ::Omnira::DataSerialization::internal::HasBits<1> _has_bits_;
    mutable ::Omnira::DataSerialization::internal::CachedSize _cached_size_;
    ::builra3::Label* label_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_builra3_2fEngineInternal_2eproto;
};
// -------------------------------------------------------------------

class TaskArtifactRequest final : public ::Omnira::DataSerialization::Message
/* @@protoc_insertion_point(class_definition:builra3.TaskArtifactRequest) */ {
 public:
  inline TaskArtifactRequest() : TaskArtifactRequest(nullptr) {}
  ~TaskArtifactRequest() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TaskArtifactRequest(
      ::Omnira::DataSerialization::internal::ConstantInitialized);

  inline TaskArtifactRequest(const TaskArtifactRequest& from) : TaskArtifactRequest(nullptr, from) {}
  inline TaskArtifactRequest(TaskArtifactRequest&& from) noexcept
      : TaskArtifactRequest(nullptr, std::move(from)) {}
  inline TaskArtifactRequest& operator=(const TaskArtifactRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline TaskArtifactRequest& operator=(TaskArtifactRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::Omnira::DataSerialization::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::Omnira::DataSerialization::UnknownFieldSet>(::Omnira::DataSerialization::UnknownFieldSet::default_instance);
  }
  inline ::Omnira::DataSerialization::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::Omnira::DataSerialization::UnknownFieldSet>();
  }

  static const ::Omnira::DataSerialization::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::Omnira::DataSerialization::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::Omnira::DataSerialization::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TaskArtifactRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const TaskArtifactRequest* internal_default_instance() {
    return reinterpret_cast<const TaskArtifactRequest*>(
        &_TaskArtifactRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(TaskArtifactRequest& a, TaskArtifactRequest& b) { a.Swap(&b); }
  inline void Swap(TaskArtifactRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::Omnira::DataSerialization::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TaskArtifactRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TaskArtifactRequest* New(::Omnira::DataSerialization::Arena* arena = nullptr) const final {
    return ::Omnira::DataSerialization::Message::DefaultConstruct<TaskArtifactRequest>(arena);
  }
  using ::Omnira::DataSerialization::Message::CopyFrom;
  void CopyFrom(const TaskArtifactRequest& from);
  using ::Omnira::DataSerialization::Message::MergeFrom;
  void MergeFrom(const TaskArtifactRequest& from) { TaskArtifactRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::Omnira::DataSerialization::MessageLite& to_msg,
      const ::Omnira::DataSerialization::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::Omnira::DataSerialization::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::Omnira::DataSerialization::Arena* arena);
  void SharedDtor();
  void InternalSwap(TaskArtifactRequest* other);
 private:
  friend class ::Omnira::DataSerialization::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "builra3.TaskArtifactRequest"; }

 protected:
  explicit TaskArtifactRequest(::Omnira::DataSerialization::Arena* arena);
  TaskArtifactRequest(::Omnira::DataSerialization::Arena* arena, const TaskArtifactRequest& from);
  TaskArtifactRequest(::Omnira::DataSerialization::Arena* arena, TaskArtifactRequest&& from) noexcept
      : TaskArtifactRequest(arena) {
    *this = ::std::move(from);
  }
  const ::Omnira::DataSerialization::Message::ClassData* GetClassData() const final;

 public:
  ::Omnira::DataSerialization::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLabelFieldNumber = 1,
  };
  // .builra3.Label label = 1;
  bool has_label() const;
  void clear_label() ;
  const ::builra3::Label& label() const;
  PROTOBUF_NODISCARD ::builra3::Label* release_label();
  ::builra3::Label* mutable_label();
  void set_allocated_label(::builra3::Label* value);
  void unsafe_arena_set_allocated_label(::builra3::Label* value);
  ::builra3::Label* unsafe_arena_release_label();

  private:
  const ::builra3::Label& _internal_label() const;
  ::builra3::Label* _internal_mutable_label();

  public:
  // @@protoc_insertion_point(class_scope:builra3.TaskArtifactRequest)
 private:
  class _Internal;
  friend class ::Omnira::DataSerialization::internal::TcParser;
  static const ::Omnira::DataSerialization::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_TaskArtifactRequest_default_instance_;

  friend class ::Omnira::DataSerialization::MessageLite;
  friend class ::Omnira::DataSerialization::Arena;
  template <typename T>
  friend class ::Omnira::DataSerialization::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::Omnira::DataSerialization::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::Omnira::DataSerialization::internal::InternalVisibility visibility,
                          ::Omnira::DataSerialization::Arena* arena);
    inline explicit Impl_(::Omnira::DataSerialization::internal::InternalVisibility visibility,
                          ::Omnira::DataSerialization::Arena* arena, const Impl_& from,
                          const TaskArtifactRequest& from_msg);
    ::Omnira::DataSerialization::internal::HasBits<1> _has_bits_;
    mutable ::Omnira::DataSerialization::internal::CachedSize _cached_size_;
    ::builra3::Label* label_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_builra3_2fEngineInternal_2eproto;
};
// -------------------------------------------------------------------

class TaskRequest final : public ::Omnira::DataSerialization::Message
/* @@protoc_insertion_point(class_definition:builra3.TaskRequest) */ {
 public:
  inline TaskRequest() : TaskRequest(nullptr) {}
  ~TaskRequest() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TaskRequest(
      ::Omnira::DataSerialization::internal::ConstantInitialized);

  inline TaskRequest(const TaskRequest& from) : TaskRequest(nullptr, from) {}
  inline TaskRequest(TaskRequest&& from) noexcept
      : TaskRequest(nullptr, std::move(from)) {}
  inline TaskRequest& operator=(const TaskRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline TaskRequest& operator=(TaskRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::Omnira::DataSerialization::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::Omnira::DataSerialization::UnknownFieldSet>(::Omnira::DataSerialization::UnknownFieldSet::default_instance);
  }
  inline ::Omnira::DataSerialization::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::Omnira::DataSerialization::UnknownFieldSet>();
  }

  static const ::Omnira::DataSerialization::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::Omnira::DataSerialization::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::Omnira::DataSerialization::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TaskRequest& default_instance() {
    return *internal_default_instance();
  }
  enum DetailsCase {
    kArtifact = 2,
    kRule = 3,
    kAction = 4,
    DETAILS_NOT_SET = 0,
  };
  static inline const TaskRequest* internal_default_instance() {
    return reinterpret_cast<const TaskRequest*>(
        &_TaskRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(TaskRequest& a, TaskRequest& b) { a.Swap(&b); }
  inline void Swap(TaskRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::Omnira::DataSerialization::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TaskRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TaskRequest* New(::Omnira::DataSerialization::Arena* arena = nullptr) const final {
    return ::Omnira::DataSerialization::Message::DefaultConstruct<TaskRequest>(arena);
  }
  using ::Omnira::DataSerialization::Message::CopyFrom;
  void CopyFrom(const TaskRequest& from);
  using ::Omnira::DataSerialization::Message::MergeFrom;
  void MergeFrom(const TaskRequest& from) { TaskRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::Omnira::DataSerialization::MessageLite& to_msg,
      const ::Omnira::DataSerialization::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::Omnira::DataSerialization::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::Omnira::DataSerialization::Arena* arena);
  void SharedDtor();
  void InternalSwap(TaskRequest* other);
 private:
  friend class ::Omnira::DataSerialization::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "builra3.TaskRequest"; }

 protected:
  explicit TaskRequest(::Omnira::DataSerialization::Arena* arena);
  TaskRequest(::Omnira::DataSerialization::Arena* arena, const TaskRequest& from);
  TaskRequest(::Omnira::DataSerialization::Arena* arena, TaskRequest&& from) noexcept
      : TaskRequest(arena) {
    *this = ::std::move(from);
  }
  const ::Omnira::DataSerialization::Message::ClassData* GetClassData() const final;

 public:
  ::Omnira::DataSerialization::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
    kArtifactFieldNumber = 2,
    kRuleFieldNumber = 3,
    kActionFieldNumber = 4,
  };
  // uint64 id = 1;
  void clear_id() ;
  ::uint64_t id() const;
  void set_id(::uint64_t value);

  private:
  ::uint64_t _internal_id() const;
  void _internal_set_id(::uint64_t value);

  public:
  // .builra3.TaskArtifactRequest artifact = 2;
  bool has_artifact() const;
  private:
  bool _internal_has_artifact() const;

  public:
  void clear_artifact() ;
  const ::builra3::TaskArtifactRequest& artifact() const;
  PROTOBUF_NODISCARD ::builra3::TaskArtifactRequest* release_artifact();
  ::builra3::TaskArtifactRequest* mutable_artifact();
  void set_allocated_artifact(::builra3::TaskArtifactRequest* value);
  void unsafe_arena_set_allocated_artifact(::builra3::TaskArtifactRequest* value);
  ::builra3::TaskArtifactRequest* unsafe_arena_release_artifact();

  private:
  const ::builra3::TaskArtifactRequest& _internal_artifact() const;
  ::builra3::TaskArtifactRequest* _internal_mutable_artifact();

  public:
  // .builra3.TaskRuleRequest rule = 3;
  bool has_rule() const;
  private:
  bool _internal_has_rule() const;

  public:
  void clear_rule() ;
  const ::builra3::TaskRuleRequest& rule() const;
  PROTOBUF_NODISCARD ::builra3::TaskRuleRequest* release_rule();
  ::builra3::TaskRuleRequest* mutable_rule();
  void set_allocated_rule(::builra3::TaskRuleRequest* value);
  void unsafe_arena_set_allocated_rule(::builra3::TaskRuleRequest* value);
  ::builra3::TaskRuleRequest* unsafe_arena_release_rule();

  private:
  const ::builra3::TaskRuleRequest& _internal_rule() const;
  ::builra3::TaskRuleRequest* _internal_mutable_rule();

  public:
  // .builra3.Action action = 4;
  bool has_action() const;
  private:
  bool _internal_has_action() const;

  public:
  void clear_action() ;
  const ::builra3::Action& action() const;
  PROTOBUF_NODISCARD ::builra3::Action* release_action();
  ::builra3::Action* mutable_action();
  void set_allocated_action(::builra3::Action* value);
  void unsafe_arena_set_allocated_action(::builra3::Action* value);
  ::builra3::Action* unsafe_arena_release_action();

  private:
  const ::builra3::Action& _internal_action() const;
  ::builra3::Action* _internal_mutable_action();

  public:
  void clear_details();
  DetailsCase details_case() const;
  // @@protoc_insertion_point(class_scope:builra3.TaskRequest)
 private:
  class _Internal;
  void set_has_artifact();
  void set_has_rule();
  void set_has_action();
  inline bool has_details() const;
  inline void clear_has_details();
  friend class ::Omnira::DataSerialization::internal::TcParser;
  static const ::Omnira::DataSerialization::internal::TcParseTable<
      0, 4, 3,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_TaskRequest_default_instance_;

  friend class ::Omnira::DataSerialization::MessageLite;
  friend class ::Omnira::DataSerialization::Arena;
  template <typename T>
  friend class ::Omnira::DataSerialization::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::Omnira::DataSerialization::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::Omnira::DataSerialization::internal::InternalVisibility visibility,
                          ::Omnira::DataSerialization::Arena* arena);
    inline explicit Impl_(::Omnira::DataSerialization::internal::InternalVisibility visibility,
                          ::Omnira::DataSerialization::Arena* arena, const Impl_& from,
                          const TaskRequest& from_msg);
    ::uint64_t id_;
    union DetailsUnion {
      constexpr DetailsUnion() : _constinit_{} {}
      ::Omnira::DataSerialization::internal::ConstantInitialized _constinit_;
      ::builra3::TaskArtifactRequest* artifact_;
      ::builra3::TaskRuleRequest* rule_;
      ::builra3::Action* action_;
    } details_;
    mutable ::Omnira::DataSerialization::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_builra3_2fEngineInternal_2eproto;
};
// -------------------------------------------------------------------

class TaskTransitionValue final : public ::Omnira::DataSerialization::Message
/* @@protoc_insertion_point(class_definition:builra3.TaskTransitionValue) */ {
 public:
  inline TaskTransitionValue() : TaskTransitionValue(nullptr) {}
  ~TaskTransitionValue() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TaskTransitionValue(
      ::Omnira::DataSerialization::internal::ConstantInitialized);

  inline TaskTransitionValue(const TaskTransitionValue& from) : TaskTransitionValue(nullptr, from) {}
  inline TaskTransitionValue(TaskTransitionValue&& from) noexcept
      : TaskTransitionValue(nullptr, std::move(from)) {}
  inline TaskTransitionValue& operator=(const TaskTransitionValue& from) {
    CopyFrom(from);
    return *this;
  }
  inline TaskTransitionValue& operator=(TaskTransitionValue&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::Omnira::DataSerialization::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::Omnira::DataSerialization::UnknownFieldSet>(::Omnira::DataSerialization::UnknownFieldSet::default_instance);
  }
  inline ::Omnira::DataSerialization::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::Omnira::DataSerialization::UnknownFieldSet>();
  }

  static const ::Omnira::DataSerialization::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::Omnira::DataSerialization::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::Omnira::DataSerialization::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TaskTransitionValue& default_instance() {
    return *internal_default_instance();
  }
  static inline const TaskTransitionValue* internal_default_instance() {
    return reinterpret_cast<const TaskTransitionValue*>(
        &_TaskTransitionValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(TaskTransitionValue& a, TaskTransitionValue& b) { a.Swap(&b); }
  inline void Swap(TaskTransitionValue* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::Omnira::DataSerialization::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TaskTransitionValue* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TaskTransitionValue* New(::Omnira::DataSerialization::Arena* arena = nullptr) const final {
    return ::Omnira::DataSerialization::Message::DefaultConstruct<TaskTransitionValue>(arena);
  }
  using ::Omnira::DataSerialization::Message::CopyFrom;
  void CopyFrom(const TaskTransitionValue& from);
  using ::Omnira::DataSerialization::Message::MergeFrom;
  void MergeFrom(const TaskTransitionValue& from) { TaskTransitionValue::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::Omnira::DataSerialization::MessageLite& to_msg,
      const ::Omnira::DataSerialization::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::Omnira::DataSerialization::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::Omnira::DataSerialization::Arena* arena);
  void SharedDtor();
  void InternalSwap(TaskTransitionValue* other);
 private:
  friend class ::Omnira::DataSerialization::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "builra3.TaskTransitionValue"; }

 protected:
  explicit TaskTransitionValue(::Omnira::DataSerialization::Arena* arena);
  TaskTransitionValue(::Omnira::DataSerialization::Arena* arena, const TaskTransitionValue& from);
  TaskTransitionValue(::Omnira::DataSerialization::Arena* arena, TaskTransitionValue&& from) noexcept
      : TaskTransitionValue(arena) {
    *this = ::std::move(from);
  }
  const ::Omnira::DataSerialization::Message::ClassData* GetClassData() const final;

 public:
  ::Omnira::DataSerialization::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRequestsFieldNumber = 2,
    kStateFieldNumber = 1,
  };
  // repeated .builra3.TaskRequest requests = 2;
  int requests_size() const;
  private:
  int _internal_requests_size() const;

  public:
  void clear_requests() ;
  ::builra3::TaskRequest* mutable_requests(int index);
  ::Omnira::DataSerialization::RepeatedPtrField<::builra3::TaskRequest>* mutable_requests();

  private:
  const ::Omnira::DataSerialization::RepeatedPtrField<::builra3::TaskRequest>& _internal_requests() const;
  ::Omnira::DataSerialization::RepeatedPtrField<::builra3::TaskRequest>* _internal_mutable_requests();
  public:
  const ::builra3::TaskRequest& requests(int index) const;
  ::builra3::TaskRequest* add_requests();
  const ::Omnira::DataSerialization::RepeatedPtrField<::builra3::TaskRequest>& requests() const;
  // .builra3.TaskNextState state = 1;
  bool has_state() const;
  void clear_state() ;
  const ::builra3::TaskNextState& state() const;
  PROTOBUF_NODISCARD ::builra3::TaskNextState* release_state();
  ::builra3::TaskNextState* mutable_state();
  void set_allocated_state(::builra3::TaskNextState* value);
  void unsafe_arena_set_allocated_state(::builra3::TaskNextState* value);
  ::builra3::TaskNextState* unsafe_arena_release_state();

  private:
  const ::builra3::TaskNextState& _internal_state() const;
  ::builra3::TaskNextState* _internal_mutable_state();

  public:
  // @@protoc_insertion_point(class_scope:builra3.TaskTransitionValue)
 private:
  class _Internal;
  friend class ::Omnira::DataSerialization::internal::TcParser;
  static const ::Omnira::DataSerialization::internal::TcParseTable<
      1, 2, 2,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_TaskTransitionValue_default_instance_;

  friend class ::Omnira::DataSerialization::MessageLite;
  friend class ::Omnira::DataSerialization::Arena;
  template <typename T>
  friend class ::Omnira::DataSerialization::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::Omnira::DataSerialization::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::Omnira::DataSerialization::internal::InternalVisibility visibility,
                          ::Omnira::DataSerialization::Arena* arena);
    inline explicit Impl_(::Omnira::DataSerialization::internal::InternalVisibility visibility,
                          ::Omnira::DataSerialization::Arena* arena, const Impl_& from,
                          const TaskTransitionValue& from_msg);
    ::Omnira::DataSerialization::internal::HasBits<1> _has_bits_;
    mutable ::Omnira::DataSerialization::internal::CachedSize _cached_size_;
    ::Omnira::DataSerialization::RepeatedPtrField< ::builra3::TaskRequest > requests_;
    ::builra3::TaskNextState* state_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_builra3_2fEngineInternal_2eproto;
};
// -------------------------------------------------------------------

class TaskTransitionKey final : public ::Omnira::DataSerialization::Message
/* @@protoc_insertion_point(class_definition:builra3.TaskTransitionKey) */ {
 public:
  inline TaskTransitionKey() : TaskTransitionKey(nullptr) {}
  ~TaskTransitionKey() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TaskTransitionKey(
      ::Omnira::DataSerialization::internal::ConstantInitialized);

  inline TaskTransitionKey(const TaskTransitionKey& from) : TaskTransitionKey(nullptr, from) {}
  inline TaskTransitionKey(TaskTransitionKey&& from) noexcept
      : TaskTransitionKey(nullptr, std::move(from)) {}
  inline TaskTransitionKey& operator=(const TaskTransitionKey& from) {
    CopyFrom(from);
    return *this;
  }
  inline TaskTransitionKey& operator=(TaskTransitionKey&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::Omnira::DataSerialization::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::Omnira::DataSerialization::UnknownFieldSet>(::Omnira::DataSerialization::UnknownFieldSet::default_instance);
  }
  inline ::Omnira::DataSerialization::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::Omnira::DataSerialization::UnknownFieldSet>();
  }

  static const ::Omnira::DataSerialization::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::Omnira::DataSerialization::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::Omnira::DataSerialization::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TaskTransitionKey& default_instance() {
    return *internal_default_instance();
  }
  static inline const TaskTransitionKey* internal_default_instance() {
    return reinterpret_cast<const TaskTransitionKey*>(
        &_TaskTransitionKey_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(TaskTransitionKey& a, TaskTransitionKey& b) { a.Swap(&b); }
  inline void Swap(TaskTransitionKey* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::Omnira::DataSerialization::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TaskTransitionKey* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TaskTransitionKey* New(::Omnira::DataSerialization::Arena* arena = nullptr) const final {
    return ::Omnira::DataSerialization::Message::DefaultConstruct<TaskTransitionKey>(arena);
  }
  using ::Omnira::DataSerialization::Message::CopyFrom;
  void CopyFrom(const TaskTransitionKey& from);
  using ::Omnira::DataSerialization::Message::MergeFrom;
  void MergeFrom(const TaskTransitionKey& from) { TaskTransitionKey::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::Omnira::DataSerialization::MessageLite& to_msg,
      const ::Omnira::DataSerialization::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::Omnira::DataSerialization::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::Omnira::DataSerialization::Arena* arena);
  void SharedDtor();
  void InternalSwap(TaskTransitionKey* other);
 private:
  friend class ::Omnira::DataSerialization::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "builra3.TaskTransitionKey"; }

 protected:
  explicit TaskTransitionKey(::Omnira::DataSerialization::Arena* arena);
  TaskTransitionKey(::Omnira::DataSerialization::Arena* arena, const TaskTransitionKey& from);
  TaskTransitionKey(::Omnira::DataSerialization::Arena* arena, TaskTransitionKey&& from) noexcept
      : TaskTransitionKey(arena) {
    *this = ::std::move(from);
  }
  const ::Omnira::DataSerialization::Message::ClassData* GetClassData() const final;

 public:
  ::Omnira::DataSerialization::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCtxFieldNumber = 1,
    kSignatureFieldNumber = 2,
    kInputsFieldNumber = 3,
  };
  // .builra3.TaskContext ctx = 1;
  bool has_ctx() const;
  void clear_ctx() ;
  const ::builra3::TaskContext& ctx() const;
  PROTOBUF_NODISCARD ::builra3::TaskContext* release_ctx();
  ::builra3::TaskContext* mutable_ctx();
  void set_allocated_ctx(::builra3::TaskContext* value);
  void unsafe_arena_set_allocated_ctx(::builra3::TaskContext* value);
  ::builra3::TaskContext* unsafe_arena_release_ctx();

  private:
  const ::builra3::TaskContext& _internal_ctx() const;
  ::builra3::TaskContext* _internal_mutable_ctx();

  public:
  // .builra3.Signature signature = 2;
  bool has_signature() const;
  void clear_signature() ;
  const ::builra3::Signature& signature() const;
  PROTOBUF_NODISCARD ::builra3::Signature* release_signature();
  ::builra3::Signature* mutable_signature();
  void set_allocated_signature(::builra3::Signature* value);
  void unsafe_arena_set_allocated_signature(::builra3::Signature* value);
  ::builra3::Signature* unsafe_arena_release_signature();

  private:
  const ::builra3::Signature& _internal_signature() const;
  ::builra3::Signature* _internal_mutable_signature();

  public:
  // .builra3.TaskInputs inputs = 3;
  bool has_inputs() const;
  void clear_inputs() ;
  const ::builra3::TaskInputs& inputs() const;
  PROTOBUF_NODISCARD ::builra3::TaskInputs* release_inputs();
  ::builra3::TaskInputs* mutable_inputs();
  void set_allocated_inputs(::builra3::TaskInputs* value);
  void unsafe_arena_set_allocated_inputs(::builra3::TaskInputs* value);
  ::builra3::TaskInputs* unsafe_arena_release_inputs();

  private:
  const ::builra3::TaskInputs& _internal_inputs() const;
  ::builra3::TaskInputs* _internal_mutable_inputs();

  public:
  // @@protoc_insertion_point(class_scope:builra3.TaskTransitionKey)
 private:
  class _Internal;
  friend class ::Omnira::DataSerialization::internal::TcParser;
  static const ::Omnira::DataSerialization::internal::TcParseTable<
      2, 3, 3,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_TaskTransitionKey_default_instance_;

  friend class ::Omnira::DataSerialization::MessageLite;
  friend class ::Omnira::DataSerialization::Arena;
  template <typename T>
  friend class ::Omnira::DataSerialization::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::Omnira::DataSerialization::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::Omnira::DataSerialization::internal::InternalVisibility visibility,
                          ::Omnira::DataSerialization::Arena* arena);
    inline explicit Impl_(::Omnira::DataSerialization::internal::InternalVisibility visibility,
                          ::Omnira::DataSerialization::Arena* arena, const Impl_& from,
                          const TaskTransitionKey& from_msg);
    ::Omnira::DataSerialization::internal::HasBits<1> _has_bits_;
    mutable ::Omnira::DataSerialization::internal::CachedSize _cached_size_;
    ::builra3::TaskContext* ctx_;
    ::builra3::Signature* signature_;
    ::builra3::TaskInputs* inputs_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_builra3_2fEngineInternal_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// TaskArtifactRequest

// .builra3.Label label = 1;
inline bool TaskArtifactRequest::has_label() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.label_ != nullptr);
  return value;
}
inline const ::builra3::Label& TaskArtifactRequest::_internal_label() const {
  ::Omnira::DataSerialization::internal::TSanRead(&_impl_);
  const ::builra3::Label* p = _impl_.label_;
  return p != nullptr ? *p : reinterpret_cast<const ::builra3::Label&>(::builra3::_Label_default_instance_);
}
inline const ::builra3::Label& TaskArtifactRequest::label() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:builra3.TaskArtifactRequest.label)
  return _internal_label();
}
inline void TaskArtifactRequest::unsafe_arena_set_allocated_label(::builra3::Label* value) {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(_impl_.label_);
  }
  _impl_.label_ = reinterpret_cast<::builra3::Label*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:builra3.TaskArtifactRequest.label)
}
inline ::builra3::Label* TaskArtifactRequest::release_label() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::builra3::Label* released = _impl_.label_;
  _impl_.label_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(released);
  released = ::Omnira::DataSerialization::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::Omnira::DataSerialization::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::builra3::Label* TaskArtifactRequest::unsafe_arena_release_label() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:builra3.TaskArtifactRequest.label)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::builra3::Label* temp = _impl_.label_;
  _impl_.label_ = nullptr;
  return temp;
}
inline ::builra3::Label* TaskArtifactRequest::_internal_mutable_label() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (_impl_.label_ == nullptr) {
    auto* p = ::Omnira::DataSerialization::Message::DefaultConstruct<::builra3::Label>(GetArena());
    _impl_.label_ = reinterpret_cast<::builra3::Label*>(p);
  }
  return _impl_.label_;
}
inline ::builra3::Label* TaskArtifactRequest::mutable_label() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::builra3::Label* _msg = _internal_mutable_label();
  // @@protoc_insertion_point(field_mutable:builra3.TaskArtifactRequest.label)
  return _msg;
}
inline void TaskArtifactRequest::set_allocated_label(::builra3::Label* value) {
  ::Omnira::DataSerialization::Arena* message_arena = GetArena();
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(_impl_.label_);
  }

  if (value != nullptr) {
    ::Omnira::DataSerialization::Arena* submessage_arena = reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::Omnira::DataSerialization::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.label_ = reinterpret_cast<::builra3::Label*>(value);
  // @@protoc_insertion_point(field_set_allocated:builra3.TaskArtifactRequest.label)
}

// -------------------------------------------------------------------

// TaskRuleRequest

// .builra3.Label label = 1;
inline bool TaskRuleRequest::has_label() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.label_ != nullptr);
  return value;
}
inline const ::builra3::Label& TaskRuleRequest::_internal_label() const {
  ::Omnira::DataSerialization::internal::TSanRead(&_impl_);
  const ::builra3::Label* p = _impl_.label_;
  return p != nullptr ? *p : reinterpret_cast<const ::builra3::Label&>(::builra3::_Label_default_instance_);
}
inline const ::builra3::Label& TaskRuleRequest::label() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:builra3.TaskRuleRequest.label)
  return _internal_label();
}
inline void TaskRuleRequest::unsafe_arena_set_allocated_label(::builra3::Label* value) {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(_impl_.label_);
  }
  _impl_.label_ = reinterpret_cast<::builra3::Label*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:builra3.TaskRuleRequest.label)
}
inline ::builra3::Label* TaskRuleRequest::release_label() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::builra3::Label* released = _impl_.label_;
  _impl_.label_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(released);
  released = ::Omnira::DataSerialization::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::Omnira::DataSerialization::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::builra3::Label* TaskRuleRequest::unsafe_arena_release_label() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:builra3.TaskRuleRequest.label)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::builra3::Label* temp = _impl_.label_;
  _impl_.label_ = nullptr;
  return temp;
}
inline ::builra3::Label* TaskRuleRequest::_internal_mutable_label() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (_impl_.label_ == nullptr) {
    auto* p = ::Omnira::DataSerialization::Message::DefaultConstruct<::builra3::Label>(GetArena());
    _impl_.label_ = reinterpret_cast<::builra3::Label*>(p);
  }
  return _impl_.label_;
}
inline ::builra3::Label* TaskRuleRequest::mutable_label() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::builra3::Label* _msg = _internal_mutable_label();
  // @@protoc_insertion_point(field_mutable:builra3.TaskRuleRequest.label)
  return _msg;
}
inline void TaskRuleRequest::set_allocated_label(::builra3::Label* value) {
  ::Omnira::DataSerialization::Arena* message_arena = GetArena();
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(_impl_.label_);
  }

  if (value != nullptr) {
    ::Omnira::DataSerialization::Arena* submessage_arena = reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::Omnira::DataSerialization::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.label_ = reinterpret_cast<::builra3::Label*>(value);
  // @@protoc_insertion_point(field_set_allocated:builra3.TaskRuleRequest.label)
}

// -------------------------------------------------------------------

// TaskRequest

// uint64 id = 1;
inline void TaskRequest::clear_id() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  _impl_.id_ = ::uint64_t{0u};
}
inline ::uint64_t TaskRequest::id() const {
  // @@protoc_insertion_point(field_get:builra3.TaskRequest.id)
  return _internal_id();
}
inline void TaskRequest::set_id(::uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:builra3.TaskRequest.id)
}
inline ::uint64_t TaskRequest::_internal_id() const {
  ::Omnira::DataSerialization::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void TaskRequest::_internal_set_id(::uint64_t value) {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// .builra3.TaskArtifactRequest artifact = 2;
inline bool TaskRequest::has_artifact() const {
  return details_case() == kArtifact;
}
inline bool TaskRequest::_internal_has_artifact() const {
  return details_case() == kArtifact;
}
inline void TaskRequest::set_has_artifact() {
  _impl_._oneof_case_[0] = kArtifact;
}
inline void TaskRequest::clear_artifact() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (details_case() == kArtifact) {
    if (GetArena() == nullptr) {
      delete _impl_.details_.artifact_;
    } else if (::Omnira::DataSerialization::internal::DebugHardenClearOneofMessageOnArena()) {
      ::Omnira::DataSerialization::internal::MaybePoisonAfterClear(_impl_.details_.artifact_);
    }
    clear_has_details();
  }
}
inline ::builra3::TaskArtifactRequest* TaskRequest::release_artifact() {
  // @@protoc_insertion_point(field_release:builra3.TaskRequest.artifact)
  if (details_case() == kArtifact) {
    clear_has_details();
    auto* temp = _impl_.details_.artifact_;
    if (GetArena() != nullptr) {
      temp = ::Omnira::DataSerialization::internal::DuplicateIfNonNull(temp);
    }
    _impl_.details_.artifact_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::builra3::TaskArtifactRequest& TaskRequest::_internal_artifact() const {
  return details_case() == kArtifact ? *_impl_.details_.artifact_ : reinterpret_cast<::builra3::TaskArtifactRequest&>(::builra3::_TaskArtifactRequest_default_instance_);
}
inline const ::builra3::TaskArtifactRequest& TaskRequest::artifact() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:builra3.TaskRequest.artifact)
  return _internal_artifact();
}
inline ::builra3::TaskArtifactRequest* TaskRequest::unsafe_arena_release_artifact() {
  // @@protoc_insertion_point(field_unsafe_arena_release:builra3.TaskRequest.artifact)
  if (details_case() == kArtifact) {
    clear_has_details();
    auto* temp = _impl_.details_.artifact_;
    _impl_.details_.artifact_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void TaskRequest::unsafe_arena_set_allocated_artifact(::builra3::TaskArtifactRequest* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_details();
  if (value) {
    set_has_artifact();
    _impl_.details_.artifact_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:builra3.TaskRequest.artifact)
}
inline ::builra3::TaskArtifactRequest* TaskRequest::_internal_mutable_artifact() {
  if (details_case() != kArtifact) {
    clear_details();
    set_has_artifact();
    _impl_.details_.artifact_ =
        ::Omnira::DataSerialization::Message::DefaultConstruct<::builra3::TaskArtifactRequest>(GetArena());
  }
  return _impl_.details_.artifact_;
}
inline ::builra3::TaskArtifactRequest* TaskRequest::mutable_artifact() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::builra3::TaskArtifactRequest* _msg = _internal_mutable_artifact();
  // @@protoc_insertion_point(field_mutable:builra3.TaskRequest.artifact)
  return _msg;
}

// .builra3.TaskRuleRequest rule = 3;
inline bool TaskRequest::has_rule() const {
  return details_case() == kRule;
}
inline bool TaskRequest::_internal_has_rule() const {
  return details_case() == kRule;
}
inline void TaskRequest::set_has_rule() {
  _impl_._oneof_case_[0] = kRule;
}
inline void TaskRequest::clear_rule() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (details_case() == kRule) {
    if (GetArena() == nullptr) {
      delete _impl_.details_.rule_;
    } else if (::Omnira::DataSerialization::internal::DebugHardenClearOneofMessageOnArena()) {
      ::Omnira::DataSerialization::internal::MaybePoisonAfterClear(_impl_.details_.rule_);
    }
    clear_has_details();
  }
}
inline ::builra3::TaskRuleRequest* TaskRequest::release_rule() {
  // @@protoc_insertion_point(field_release:builra3.TaskRequest.rule)
  if (details_case() == kRule) {
    clear_has_details();
    auto* temp = _impl_.details_.rule_;
    if (GetArena() != nullptr) {
      temp = ::Omnira::DataSerialization::internal::DuplicateIfNonNull(temp);
    }
    _impl_.details_.rule_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::builra3::TaskRuleRequest& TaskRequest::_internal_rule() const {
  return details_case() == kRule ? *_impl_.details_.rule_ : reinterpret_cast<::builra3::TaskRuleRequest&>(::builra3::_TaskRuleRequest_default_instance_);
}
inline const ::builra3::TaskRuleRequest& TaskRequest::rule() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:builra3.TaskRequest.rule)
  return _internal_rule();
}
inline ::builra3::TaskRuleRequest* TaskRequest::unsafe_arena_release_rule() {
  // @@protoc_insertion_point(field_unsafe_arena_release:builra3.TaskRequest.rule)
  if (details_case() == kRule) {
    clear_has_details();
    auto* temp = _impl_.details_.rule_;
    _impl_.details_.rule_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void TaskRequest::unsafe_arena_set_allocated_rule(::builra3::TaskRuleRequest* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_details();
  if (value) {
    set_has_rule();
    _impl_.details_.rule_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:builra3.TaskRequest.rule)
}
inline ::builra3::TaskRuleRequest* TaskRequest::_internal_mutable_rule() {
  if (details_case() != kRule) {
    clear_details();
    set_has_rule();
    _impl_.details_.rule_ =
        ::Omnira::DataSerialization::Message::DefaultConstruct<::builra3::TaskRuleRequest>(GetArena());
  }
  return _impl_.details_.rule_;
}
inline ::builra3::TaskRuleRequest* TaskRequest::mutable_rule() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::builra3::TaskRuleRequest* _msg = _internal_mutable_rule();
  // @@protoc_insertion_point(field_mutable:builra3.TaskRequest.rule)
  return _msg;
}

// .builra3.Action action = 4;
inline bool TaskRequest::has_action() const {
  return details_case() == kAction;
}
inline bool TaskRequest::_internal_has_action() const {
  return details_case() == kAction;
}
inline void TaskRequest::set_has_action() {
  _impl_._oneof_case_[0] = kAction;
}
inline ::builra3::Action* TaskRequest::release_action() {
  // @@protoc_insertion_point(field_release:builra3.TaskRequest.action)
  if (details_case() == kAction) {
    clear_has_details();
    auto* temp = _impl_.details_.action_;
    if (GetArena() != nullptr) {
      temp = ::Omnira::DataSerialization::internal::DuplicateIfNonNull(temp);
    }
    _impl_.details_.action_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::builra3::Action& TaskRequest::_internal_action() const {
  return details_case() == kAction ? *_impl_.details_.action_ : reinterpret_cast<::builra3::Action&>(::builra3::_Action_default_instance_);
}
inline const ::builra3::Action& TaskRequest::action() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:builra3.TaskRequest.action)
  return _internal_action();
}
inline ::builra3::Action* TaskRequest::unsafe_arena_release_action() {
  // @@protoc_insertion_point(field_unsafe_arena_release:builra3.TaskRequest.action)
  if (details_case() == kAction) {
    clear_has_details();
    auto* temp = _impl_.details_.action_;
    _impl_.details_.action_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void TaskRequest::unsafe_arena_set_allocated_action(::builra3::Action* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_details();
  if (value) {
    set_has_action();
    _impl_.details_.action_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:builra3.TaskRequest.action)
}
inline ::builra3::Action* TaskRequest::_internal_mutable_action() {
  if (details_case() != kAction) {
    clear_details();
    set_has_action();
    _impl_.details_.action_ =
        ::Omnira::DataSerialization::Message::DefaultConstruct<::builra3::Action>(GetArena());
  }
  return _impl_.details_.action_;
}
inline ::builra3::Action* TaskRequest::mutable_action() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::builra3::Action* _msg = _internal_mutable_action();
  // @@protoc_insertion_point(field_mutable:builra3.TaskRequest.action)
  return _msg;
}

inline bool TaskRequest::has_details() const {
  return details_case() != DETAILS_NOT_SET;
}
inline void TaskRequest::clear_has_details() {
  _impl_._oneof_case_[0] = DETAILS_NOT_SET;
}
inline TaskRequest::DetailsCase TaskRequest::details_case() const {
  return TaskRequest::DetailsCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// TaskTransitionKey

// .builra3.TaskContext ctx = 1;
inline bool TaskTransitionKey::has_ctx() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.ctx_ != nullptr);
  return value;
}
inline const ::builra3::TaskContext& TaskTransitionKey::_internal_ctx() const {
  ::Omnira::DataSerialization::internal::TSanRead(&_impl_);
  const ::builra3::TaskContext* p = _impl_.ctx_;
  return p != nullptr ? *p : reinterpret_cast<const ::builra3::TaskContext&>(::builra3::_TaskContext_default_instance_);
}
inline const ::builra3::TaskContext& TaskTransitionKey::ctx() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:builra3.TaskTransitionKey.ctx)
  return _internal_ctx();
}
inline void TaskTransitionKey::unsafe_arena_set_allocated_ctx(::builra3::TaskContext* value) {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(_impl_.ctx_);
  }
  _impl_.ctx_ = reinterpret_cast<::builra3::TaskContext*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:builra3.TaskTransitionKey.ctx)
}
inline ::builra3::TaskContext* TaskTransitionKey::release_ctx() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::builra3::TaskContext* released = _impl_.ctx_;
  _impl_.ctx_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(released);
  released = ::Omnira::DataSerialization::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::Omnira::DataSerialization::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::builra3::TaskContext* TaskTransitionKey::unsafe_arena_release_ctx() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:builra3.TaskTransitionKey.ctx)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::builra3::TaskContext* temp = _impl_.ctx_;
  _impl_.ctx_ = nullptr;
  return temp;
}
inline ::builra3::TaskContext* TaskTransitionKey::_internal_mutable_ctx() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (_impl_.ctx_ == nullptr) {
    auto* p = ::Omnira::DataSerialization::Message::DefaultConstruct<::builra3::TaskContext>(GetArena());
    _impl_.ctx_ = reinterpret_cast<::builra3::TaskContext*>(p);
  }
  return _impl_.ctx_;
}
inline ::builra3::TaskContext* TaskTransitionKey::mutable_ctx() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::builra3::TaskContext* _msg = _internal_mutable_ctx();
  // @@protoc_insertion_point(field_mutable:builra3.TaskTransitionKey.ctx)
  return _msg;
}
inline void TaskTransitionKey::set_allocated_ctx(::builra3::TaskContext* value) {
  ::Omnira::DataSerialization::Arena* message_arena = GetArena();
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(_impl_.ctx_);
  }

  if (value != nullptr) {
    ::Omnira::DataSerialization::Arena* submessage_arena = reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::Omnira::DataSerialization::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.ctx_ = reinterpret_cast<::builra3::TaskContext*>(value);
  // @@protoc_insertion_point(field_set_allocated:builra3.TaskTransitionKey.ctx)
}

// .builra3.Signature signature = 2;
inline bool TaskTransitionKey::has_signature() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.signature_ != nullptr);
  return value;
}
inline const ::builra3::Signature& TaskTransitionKey::_internal_signature() const {
  ::Omnira::DataSerialization::internal::TSanRead(&_impl_);
  const ::builra3::Signature* p = _impl_.signature_;
  return p != nullptr ? *p : reinterpret_cast<const ::builra3::Signature&>(::builra3::_Signature_default_instance_);
}
inline const ::builra3::Signature& TaskTransitionKey::signature() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:builra3.TaskTransitionKey.signature)
  return _internal_signature();
}
inline void TaskTransitionKey::unsafe_arena_set_allocated_signature(::builra3::Signature* value) {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(_impl_.signature_);
  }
  _impl_.signature_ = reinterpret_cast<::builra3::Signature*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:builra3.TaskTransitionKey.signature)
}
inline ::builra3::Signature* TaskTransitionKey::release_signature() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::builra3::Signature* released = _impl_.signature_;
  _impl_.signature_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(released);
  released = ::Omnira::DataSerialization::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::Omnira::DataSerialization::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::builra3::Signature* TaskTransitionKey::unsafe_arena_release_signature() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:builra3.TaskTransitionKey.signature)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::builra3::Signature* temp = _impl_.signature_;
  _impl_.signature_ = nullptr;
  return temp;
}
inline ::builra3::Signature* TaskTransitionKey::_internal_mutable_signature() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (_impl_.signature_ == nullptr) {
    auto* p = ::Omnira::DataSerialization::Message::DefaultConstruct<::builra3::Signature>(GetArena());
    _impl_.signature_ = reinterpret_cast<::builra3::Signature*>(p);
  }
  return _impl_.signature_;
}
inline ::builra3::Signature* TaskTransitionKey::mutable_signature() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::builra3::Signature* _msg = _internal_mutable_signature();
  // @@protoc_insertion_point(field_mutable:builra3.TaskTransitionKey.signature)
  return _msg;
}
inline void TaskTransitionKey::set_allocated_signature(::builra3::Signature* value) {
  ::Omnira::DataSerialization::Arena* message_arena = GetArena();
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(_impl_.signature_);
  }

  if (value != nullptr) {
    ::Omnira::DataSerialization::Arena* submessage_arena = reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::Omnira::DataSerialization::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.signature_ = reinterpret_cast<::builra3::Signature*>(value);
  // @@protoc_insertion_point(field_set_allocated:builra3.TaskTransitionKey.signature)
}

// .builra3.TaskInputs inputs = 3;
inline bool TaskTransitionKey::has_inputs() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.inputs_ != nullptr);
  return value;
}
inline const ::builra3::TaskInputs& TaskTransitionKey::_internal_inputs() const {
  ::Omnira::DataSerialization::internal::TSanRead(&_impl_);
  const ::builra3::TaskInputs* p = _impl_.inputs_;
  return p != nullptr ? *p : reinterpret_cast<const ::builra3::TaskInputs&>(::builra3::_TaskInputs_default_instance_);
}
inline const ::builra3::TaskInputs& TaskTransitionKey::inputs() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:builra3.TaskTransitionKey.inputs)
  return _internal_inputs();
}
inline void TaskTransitionKey::unsafe_arena_set_allocated_inputs(::builra3::TaskInputs* value) {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(_impl_.inputs_);
  }
  _impl_.inputs_ = reinterpret_cast<::builra3::TaskInputs*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:builra3.TaskTransitionKey.inputs)
}
inline ::builra3::TaskInputs* TaskTransitionKey::release_inputs() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::builra3::TaskInputs* released = _impl_.inputs_;
  _impl_.inputs_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(released);
  released = ::Omnira::DataSerialization::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::Omnira::DataSerialization::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::builra3::TaskInputs* TaskTransitionKey::unsafe_arena_release_inputs() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:builra3.TaskTransitionKey.inputs)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::builra3::TaskInputs* temp = _impl_.inputs_;
  _impl_.inputs_ = nullptr;
  return temp;
}
inline ::builra3::TaskInputs* TaskTransitionKey::_internal_mutable_inputs() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (_impl_.inputs_ == nullptr) {
    auto* p = ::Omnira::DataSerialization::Message::DefaultConstruct<::builra3::TaskInputs>(GetArena());
    _impl_.inputs_ = reinterpret_cast<::builra3::TaskInputs*>(p);
  }
  return _impl_.inputs_;
}
inline ::builra3::TaskInputs* TaskTransitionKey::mutable_inputs() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::builra3::TaskInputs* _msg = _internal_mutable_inputs();
  // @@protoc_insertion_point(field_mutable:builra3.TaskTransitionKey.inputs)
  return _msg;
}
inline void TaskTransitionKey::set_allocated_inputs(::builra3::TaskInputs* value) {
  ::Omnira::DataSerialization::Arena* message_arena = GetArena();
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(_impl_.inputs_);
  }

  if (value != nullptr) {
    ::Omnira::DataSerialization::Arena* submessage_arena = reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::Omnira::DataSerialization::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.inputs_ = reinterpret_cast<::builra3::TaskInputs*>(value);
  // @@protoc_insertion_point(field_set_allocated:builra3.TaskTransitionKey.inputs)
}

// -------------------------------------------------------------------

// TaskTransitionValue

// .builra3.TaskNextState state = 1;
inline bool TaskTransitionValue::has_state() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.state_ != nullptr);
  return value;
}
inline const ::builra3::TaskNextState& TaskTransitionValue::_internal_state() const {
  ::Omnira::DataSerialization::internal::TSanRead(&_impl_);
  const ::builra3::TaskNextState* p = _impl_.state_;
  return p != nullptr ? *p : reinterpret_cast<const ::builra3::TaskNextState&>(::builra3::_TaskNextState_default_instance_);
}
inline const ::builra3::TaskNextState& TaskTransitionValue::state() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:builra3.TaskTransitionValue.state)
  return _internal_state();
}
inline void TaskTransitionValue::unsafe_arena_set_allocated_state(::builra3::TaskNextState* value) {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(_impl_.state_);
  }
  _impl_.state_ = reinterpret_cast<::builra3::TaskNextState*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:builra3.TaskTransitionValue.state)
}
inline ::builra3::TaskNextState* TaskTransitionValue::release_state() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::builra3::TaskNextState* released = _impl_.state_;
  _impl_.state_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(released);
  released = ::Omnira::DataSerialization::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::Omnira::DataSerialization::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::builra3::TaskNextState* TaskTransitionValue::unsafe_arena_release_state() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:builra3.TaskTransitionValue.state)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::builra3::TaskNextState* temp = _impl_.state_;
  _impl_.state_ = nullptr;
  return temp;
}
inline ::builra3::TaskNextState* TaskTransitionValue::_internal_mutable_state() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (_impl_.state_ == nullptr) {
    auto* p = ::Omnira::DataSerialization::Message::DefaultConstruct<::builra3::TaskNextState>(GetArena());
    _impl_.state_ = reinterpret_cast<::builra3::TaskNextState*>(p);
  }
  return _impl_.state_;
}
inline ::builra3::TaskNextState* TaskTransitionValue::mutable_state() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::builra3::TaskNextState* _msg = _internal_mutable_state();
  // @@protoc_insertion_point(field_mutable:builra3.TaskTransitionValue.state)
  return _msg;
}
inline void TaskTransitionValue::set_allocated_state(::builra3::TaskNextState* value) {
  ::Omnira::DataSerialization::Arena* message_arena = GetArena();
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(_impl_.state_);
  }

  if (value != nullptr) {
    ::Omnira::DataSerialization::Arena* submessage_arena = reinterpret_cast<::Omnira::DataSerialization::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::Omnira::DataSerialization::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.state_ = reinterpret_cast<::builra3::TaskNextState*>(value);
  // @@protoc_insertion_point(field_set_allocated:builra3.TaskTransitionValue.state)
}

// repeated .builra3.TaskRequest requests = 2;
inline int TaskTransitionValue::_internal_requests_size() const {
  return _internal_requests().size();
}
inline int TaskTransitionValue::requests_size() const {
  return _internal_requests_size();
}
inline void TaskTransitionValue::clear_requests() {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  _impl_.requests_.Clear();
}
inline ::builra3::TaskRequest* TaskTransitionValue::mutable_requests(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:builra3.TaskTransitionValue.requests)
  return _internal_mutable_requests()->Mutable(index);
}
inline ::Omnira::DataSerialization::RepeatedPtrField<::builra3::TaskRequest>* TaskTransitionValue::mutable_requests()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:builra3.TaskTransitionValue.requests)
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  return _internal_mutable_requests();
}
inline const ::builra3::TaskRequest& TaskTransitionValue::requests(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:builra3.TaskTransitionValue.requests)
  return _internal_requests().Get(index);
}
inline ::builra3::TaskRequest* TaskTransitionValue::add_requests() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Omnira::DataSerialization::internal::TSanWrite(&_impl_);
  ::builra3::TaskRequest* _add = _internal_mutable_requests()->Add();
  // @@protoc_insertion_point(field_add:builra3.TaskTransitionValue.requests)
  return _add;
}
inline const ::Omnira::DataSerialization::RepeatedPtrField<::builra3::TaskRequest>& TaskTransitionValue::requests() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:builra3.TaskTransitionValue.requests)
  return _internal_requests();
}
inline const ::Omnira::DataSerialization::RepeatedPtrField<::builra3::TaskRequest>&
TaskTransitionValue::_internal_requests() const {
  ::Omnira::DataSerialization::internal::TSanRead(&_impl_);
  return _impl_.requests_;
}
inline ::Omnira::DataSerialization::RepeatedPtrField<::builra3::TaskRequest>*
TaskTransitionValue::_internal_mutable_requests() {
  ::Omnira::DataSerialization::internal::TSanRead(&_impl_);
  return &_impl_.requests_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace builra3


// @@protoc_insertion_point(global_scope)

#include "Omnira/DataSerialization/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_builra3_2fEngineInternal_2eproto_2epb_2eh
